### ISSUE TITLE
Question about train.csv

### ISSUE THREAD

**Issue by Yangxin666** [VanshRamani/Molmerger-Solubility-Prediction#1]
Could the authors please update the training dataset train.csv? It seems that something irrelevant was put there. Thanks!

**Comment by VanshRamani** [comment]
Hi @Yangxin666, I apologize for my error. 
I have re-uploaded the correct files. 

Any reviews on the same would be highly appreciated!
Feel free to contact for anything else at vanshramani27@gmail.com.

Best Regards,
Vansh
